/* Mandala Channel — public content renderer for the new homepage */
(function(){"use strict";
const cfg=window.MANDALA_CONFIG||{},URL=cfg.SUPABASE_URL||"",KEY=cfg.SUPABASE_PUBLISHABLE_KEY||cfg.SUPABASE_ANON_KEY||"",FALLBACK="https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=85",home=document.body?.dataset.base==="./";let db,promise,data={articles:[],videos:[],playlists:[],podcasts:[],topics:[],categories:[]};
const esc=v=>String(v??"").replace(/[&<>\"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[x]));
const yt=v=>{const s=String(v||"").trim();if(/^[\w-]{11}$/.test(s))return s;try{const u=new URL(s),h=u.hostname.replace(/^www\./,"");return h==="youtu.be"?u.pathname.slice(1):u.searchParams.get("v")||(u.pathname.match(/\/(?:embed|shorts)\/([^/]+)/)||[])[1]||""}catch{return""}};
const image=v=>v?.cover_image_url||v?.thumbnail_url||(yt(v?.youtube_video_id||v?.youtube_url)?`https://i.ytimg.com/vi/${yt(v.youtube_video_id||v.youtube_url)}/hqdefault.jpg`:FALLBACK);
async function client(){if(db)return db;if(promise)return promise;if(!URL||!KEY)throw Error("Konfigurasi Supabase belum tersedia.");promise=(async()=>{if(!window.supabase?.createClient){await new Promise((ok,no)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=ok;s.onerror=no;document.head.appendChild(s)})}return db=window.supabase.createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}})})();return promise}
async function table(name,select,order="published_at"){const q=(await client()).from(name).select(select);const r=order?await q.order(order,{ascending:false,nullsFirst:false}):await q;if(r.error)throw r.error;return r.data||[]}
function cats(items){return Object.fromEntries(items.map(x=>[x.id,x]))}
function renderStories(A,C){const el=document.getElementById("latestStories");if(!el)return;const list=A.slice(0,4);if(!list.length)return;el.innerHTML=list.map((a,i)=>`<article class="story-card${i===0?" story-feature":""}><a href="pages/artikel-detail.html${a.slug?`?slug=${encodeURIComponent(a.slug)}`:""}"><div class="story-photo"><img src="${esc(image(a))}" alt="${esc(a.title)}" loading="${i<2?"eager":"lazy"}"></div><div class="story-copy"><span>${esc(C[a.category_id]?.name||"ARTIKEL")}</span><h3>${esc(a.title)}</h3>${i===0?`<p>Mandala Channel</p>`:""}</div></a></article>`).join("")}
function renderVideos(V,C){const el=document.getElementById("videosContainer");if(!el)return;const list=V.slice(0,3);if(!list.length)return;el.innerHTML=`<article class="visual-main"><a href="pages/video.html"><div><img src="${esc(image(list[0]))}" alt="${esc(list[0].title)}"><b class="play-button">▶</b></div><span>${esc(C[list[0].category_id]?.name||"MANDALA VIDEO")}</span><h3>${esc(list[0].title)}</h3><p>${esc(list[0].description||"Kisah, perjalanan dan percakapan dalam format visual.")}</p></a></article><div class="visual-side">${list.slice(1).map(v=>`<article><a href="pages/video.html"><img src="${esc(image(v))}" alt="${esc(v.title)}"><span>${esc(C[v.category_id]?.name||"VIDEO")}</span><h3>${esc(v.title)}</h3></a></article>`).join("")}</div>`}
function renderPlaylists(P){const el=document.getElementById("playlistTrack");if(!el)return;const list=P.slice(0,8);if(!list.length)return;el.innerHTML=list.map(p=>`<a class="rail-card" href="pages/playlist.html${p.slug?`?slug=${encodeURIComponent(p.slug)}`:""}"><img src="${esc(p.cover_image_url||FALLBACK)}" alt="${esc(p.title)}" loading="lazy"><span>${esc(p.category||"MANDALA")}</span><h3>${esc(p.title)}</h3></a>`).join("")}
function renderTopics(T){const el=document.getElementById("topicsContainer");if(!el)return;el.innerHTML=T.slice(0,8).map((t,i)=>`<a href="topics/${encodeURIComponent(t.slug||"")}.html"><span>${esc(t.name)}</span><b>${String(i+1).padStart(2,"0")}</b></a>`).join("")}
function renderPodcasts(P){const el=document.getElementById("podcastsContainer");if(!el)return;if(!P.length)return;el.innerHTML=P.slice(0,4).map((p,i)=>`<article class="audio-card${i?" simple":""}">${i===0?`<img src="${esc(p.cover_image_url||FALLBACK)}" alt="${esc(p.title)}" loading="lazy">`:""}<div><span>PODCAST</span><h3>${esc(p.title)}</h3><p>${esc(p.description||"Dengarkan percakapan Mandala Channel.")}</p>${p.audio_url?`<audio preload="none" src="${esc(/^https?:/i.test(p.audio_url)?p.audio_url:`${URL}/storage/v1/object/public/podcast-audio/${String(p.audio_url).replace(/^\//,"")}`)}"></audio>`:""}<button class="audio-play" type="button">▶ PUTAR</button></div></article>`).join("");el.querySelectorAll(".audio-card").forEach(card=>{const a=card.querySelector("audio"),b=card.querySelector(".audio-play");if(!a)return;b.onclick=()=>{if(a.paused)a.play();else a.pause();b.textContent=a.paused?"▶ PUTAR":"Ⅱ JEDA"};a.onended=()=>b.textContent="▶ PUTAR"})}
async function loadHomeData(){if(!home)return data;try{const[A,V,P,C]=await Promise.all([table("articles","id,title,slug,excerpt,cover_image_url,category_id,published_at,created_at,status","published_at"),table("videos","id,title,slug,youtube_url,youtube_video_id,thumbnail_url,description,category_id,status,published_at,created_at","published_at"),table("playlists","id,title,slug,cover_image_url,category_id,status,published_at,created_at,sort_order","sort_order"),table("categories","id,name,slug,description,image_url,sort_order,is_active","sort_order")]);let POC=[];try{POC=await table("podcasts","id,title,slug,description,cover_image_url,audio_url,status,published_at,created_at","published_at")}catch(e){}const CC=cats(C),AA=A.filter(x=>x.status==="published"),VV=V.filter(x=>x.status==="published"),PP=P.filter(x=>x.status==="published"),TT=C.filter(x=>x.is_active!==false),DD=POC.filter(x=>x.status==="published"&&x.audio_url);data={articles:AA,videos:VV,playlists:PP,podcasts:DD,topics:TT,categories:C};window.DATA=data;window.MandalaPublicData=data;renderStories(AA,CC);renderVideos(VV,CC);renderPlaylists(PP);renderTopics(TT);renderPodcasts(DD);return data}catch(e){console.warn("Homepage live data gagal:",e.message);return data}}
window.loadHomeData=loadHomeData;window.getPublicData=()=>data;window.MandalaPublic={loadHomeData,getPublicData:()=>data};if(home){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",loadHomeData,{once:true});else loadHomeData()}
})();