import "./cms-service.js";
const CMS=window.MandalaCMS,$=id=>document.getElementById(id);
const container=$("articles-container"),message=$("page-message"),newButton=$("new-article-button"),logoutButton=$("logout-button"),refreshButton=$("refresh"),searchInput=$("search"),statusFilter=$("status-filter"),categoryFilter=$("category-filter"),resultCount=$("result-count");
let profile=null,allArticles=[],activeStatus="all";
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const date=v=>{if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"})};
const label=s=>({draft:"Draft",review:"Review",published:"Published",archived:"Archived"}[s]||s||"-");
const badge=s=>{const v=String(s||"draft").toLowerCase();return `<span class="badge badge-${["draft","review","published","archived"].includes(v)?v:"draft"}">${esc(label(v))}</span>`};
function msg(t,type=""){if(!message)return;message.textContent=t;message.className=`message ${type}`.trim()}
function stats(data){const c=s=>data.filter(a=>String(a.status||"draft").toLowerCase()===s).length;$("stat-total").textContent=data.length;$("stat-draft").textContent=c("draft");$("stat-review").textContent=c("review");$("stat-published").textContent=c("published");$("stat-archived").textContent=c("archived");$("stat-featured").textContent=data.filter(a=>a.featured).length}
function cats(data){const list=[...new Map(data.filter(a=>a.category_id).map(a=>[a.category_id,a.categories?.name||"Tanpa nama"])).entries()];categoryFilter.innerHTML='<option value="all">Semua kategori</option>'+list.sort((a,b)=>a[1].localeCompare(b[1],"id")).map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join("")}
function filtered(){const q=(searchInput?.value||"").trim().toLowerCase(),st=statusFilter?.value||"all",cat=categoryFilter?.value||"all";return allArticles.filter(a=>{const s=String(a.status||"draft").toLowerCase();if(activeStatus!=="all"&&(activeStatus==="featured"?!a.featured:s!==activeStatus))return false;if(st!=="all"&&s!==st)return false;if(cat!=="all"&&String(a.category_id)!==cat)return false;return!q||[a.title,a.slug,a.excerpt,a.content,a.categories?.name].some(v=>String(v||"").toLowerCase().includes(q))})}
function row(a){const id=esc(a.id),s=String(a.status||"draft").toLowerCase(),title=esc(a.title||"Tanpa judul"),cat=esc(a.categories?.name||"-"),ex=esc(a.excerpt||a.slug||"");let actions=`<a class="action" href="article-edit.html?id=${encodeURIComponent(a.id)}">Edit</a>`;if(profile?.role==="admin"&&s!=="published")actions+=`<button class="action" data-action="publish" data-id="${id}">Publish</button>`;if(profile?.role==="admin"&&s==="published")actions+=`<button class="action" data-action="archive" data-id="${id}">Arsipkan</button>`;if(profile?.role==="editor"&&s==="draft")actions+=`<button class="action" data-action="review" data-id="${id}">Kirim Review</button>`;if(profile?.role==="editor"&&s==="review")actions+=`<button class="action" data-action="archive" data-id="${id}">Arsipkan</button>`;if(profile?.role==="admin"&&s!=="published")actions+=`<button class="action danger" data-action="delete" data-id="${id}">Hapus</button>`;return `<tr><td><div class="article-cell">${a.cover_image_url?`<img class="article-thumb" src="${esc(a.cover_image_url)}" alt="">`:'<div class="article-thumb-fallback">ARTIKEL</div>'}<div><div class="article-name">${title}${a.featured?'<span class="featured-mark">★</span>':''}</div><div class="article-sub">${ex}</div></div></div></td><td>${badge(s)}</td><td>${cat}</td><td>${date(a.created_at)}</td><td><div class="actions">${actions}</div></td></tr>`}
function render(data){resultCount.textContent=`${data.length} artikel ditampilkan dari ${allArticles.length}`;if(!data.length){container.innerHTML='<div class="empty"><strong>Tidak ada artikel</strong>Coba ubah filter atau buat artikel baru.</div>';return}container.innerHTML=`<table class="table"><thead><tr><th>Artikel</th><th>Status</th><th>Kategori</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>${data.map(row).join("")}</tbody></table>`}
function apply(){render(filtered())}
async function load(){try{msg("Memuat artikel...");allArticles=await CMS.articles();stats(allArticles);cats(allArticles);apply();msg(`${allArticles.length} artikel tersedia.`)}catch(e){console.error(e);container.innerHTML='<div class="empty"><strong>Gagal memuat artikel</strong>Periksa koneksi Supabase dan Console.</div>';msg(e?.message||"Gagal memuat artikel.","error")}}
async function action(type,id){try{if(type==="delete"){if(profile?.role!=="admin")throw new Error("Hanya Admin yang dapat menghapus artikel.");if(!confirm("Yakin ingin menghapus artikel ini?"))return;await CMS.deleteArticle(id)}else if(type==="publish"){if(profile?.role!=="admin")throw new Error("Hanya Admin yang dapat publish artikel.");await CMS.changeStatus("articles",id,"published")}else if(type==="review"){if(profile?.role!=="editor")throw new Error("Aksi review hanya untuk Editor.");await CMS.changeStatus("articles",id,"review")}else if(type==="archive"){await CMS.changeStatus("articles",id,"archived")}else return;await load();msg("Aksi berhasil.","success")}catch(e){console.error(e);msg(e?.message||"Aksi gagal.","error")}}
container?.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(b)action(b.dataset.action,b.dataset.id)});
document.querySelectorAll(".status-tab,[data-status-card]").forEach(b=>b.addEventListener("click",()=>{activeStatus=b.dataset.status||b.dataset.statusCard||"all";document.querySelectorAll(".status-tab").forEach(x=>x.classList.toggle("active",x.dataset.status===activeStatus));if(statusFilter)statusFilter.value="all";apply()}));
searchInput?.addEventListener("input",apply);statusFilter?.addEventListener("change",()=>{activeStatus="all";document.querySelectorAll(".status-tab").forEach(x=>x.classList.toggle("active",x.dataset.status==="all"));apply()});categoryFilter?.addEventListener("change",apply);refreshButton?.addEventListener("click",load);$("clear-filters")?.addEventListener("click",()=>{searchInput.value="";statusFilter.value="all";categoryFilter.value="all";activeStatus="all";document.querySelectorAll(".status-tab").forEach(x=>x.classList.toggle("active",x.dataset.status==="all"));apply()});newButton?.addEventListener("click",()=>location.href="article-edit.html");logoutButton?.addEventListener("click",()=>CMS.logout());
async function init(){try{profile=await CMS.requireStaff();if(!profile)return;$("side-name").textContent=profile.full_name||profile.user?.email||"Pengguna";$("side-role").textContent=profile.role||"-";$("top-user").textContent=profile.full_name||profile.user?.email||"";await load()}catch(e){console.error(e);msg(e?.message||"Gagal membuka halaman artikel.","error")}}init();