import "./cms-service.js";

const CMS = window.MandalaCMS;
const container = document.getElementById("articles-container");
const message = document.getElementById("page-message");
const newButton = document.getElementById("new-article-button");
const logoutButton = document.getElementById("logout-button");
const refreshButton = document.getElementById("refresh");
const searchInput = document.getElementById("search");
const statusFilter = document.getElementById("status-filter");
const categoryFilter = document.getElementById("category-filter");
const resultCount = document.getElementById("result-count");
let profile = null;
let allArticles = [];
let activeStatus = "all";

const $ = id => document.getElementById(id);
function escapeHtml(value){return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function showMessage(text,type="info"){if(!message)return;message.textContent=text;message.className="message";if(type!=="info")message.classList.add(type);}
function formatDate(value){if(!value)return "-";const d=new Date(value);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"});}
function statusLabel(s){return ({draft:"Draft",review:"Review",published:"Published",archived:"Archived"})[s]||s||"-";}
function badge(s){const v=String(s||"draft").toLowerCase();return `<span class="badge badge-${["draft","review","published","archived"].includes(v)?v:"draft"}">${escapeHtml(statusLabel(v))}</span>`;}
function updateStats(data){const count=s=>data.filter(a=>String(a.status||"draft").toLowerCase()===s).length;$("stat-total").textContent=data.length;$("stat-draft").textContent=count("draft");$("stat-review").textContent=count("review");$("stat-published").textContent=count("published");$("stat-archived").textContent=count("archived");$("stat-featured").textContent=data.filter(a=>a.featured).length;}
function loadCategories(data){const cats=[...new Map(data.filter(a=>a.category_id).map(a=>[a.category_id,a.categories?.name||"Tanpa nama"])).entries()];categoryFilter.innerHTML='<option value="all">Semua kategori</option>'+cats.sort((a,b)=>a[1].localeCompare(b[1],"id")).map(([id,name])=>`<option value="${escapeHtml(id)}">${escapeHtml(name)}</option>`).join("");}
function filtered(){const q=(searchInput?.value||"").trim().toLowerCase();const st=statusFilter?.value||"all";const cat=categoryFilter?.value||"all";return allArticles.filter(a=>{const status=String(a.status||"draft").toLowerCase();if(activeStatus!=="all"&&(activeStatus==="featured"?!a.featured:status!==activeStatus))return false;if(st!=="all"&&status!==st)return false;if(cat!=="all"&&String(a.category_id)!==cat)return false;if(!q)return true;return [a.title,a.slug,a.excerpt,a.content,a.categories?.name].some(v=>String(v||"").toLowerCase().includes(q));});}
function render(data){if(!container)return;resultCount.textContent=`${data.length} artikel ditampilkan dari ${allArticles.length}`;if(!data.length){container.innerHTML='<div class="empty"><strong>Tidak ada artikel</strong>Coba ubah filter atau buat artikel baru.</div>';return;}container.innerHTML=`<table class="table"><thead><tr><th>Artikel</th><th>Status</th><th>Kategori</th><th>Dibuat</th><th>Aksi</th></tr></thead><tbody>${data.map(renderRow).join("")}</tbody></table>`;}
function renderRow(a){const id=escapeHtml(a.id),status=String(a.status||"draft").toLowerCase(),title=escapeHtml(a.title||"Tanpa judul"),cat=escapeHtml(a.categories?.name||"-"),excerpt=escapeHtml(a.excerpt||a.slug||"");let actions=`<a class="action" href="article-edit.html?id=${encodeURIComponent(a.id)}">Edit</a>`;if(profile?.role==="admin"&&!(["published"].includes(status)))actions+=`<button class="action" data-action="publish" data-id="${id}">Publish</button>`;if(profile?.role==="admin"&&status==="published")actions+=`<button class="action" data-action="archive" data-id="${id}">Arsipkan</button>`;if(profile?.role!=="admin"&&status==="draft")actions+=`<button class="action" data-action="review" data-id="${id}">Kirim Review</button>`;if(profile?.role!=="admin"&&status==="review")actions+=`<button class="action" data-action="archive" data-id="${id}">Arsipkan</button>`;if(status!=="published")actions+=`<button class="action danger" data-action="delete" data-id="${id}">Hapus</button>`;return `<tr><td><div class="article-cell">${a.cover_image_url?`<img class="article-thumb" src="${escapeHtml(a.cover_image_url)}" alt="">`:'<div class="article-thumb-fallback">ARTIKEL</div>'}<div><div class="article-name">${title}${a.featured?'<span class="featured-mark">★</span>':''}</div><div class="article-sub">${excerpt}</div></div></div></td><td>${badge(status)}</td><td>${cat}</td><td>${formatDate(a.created_at)}</td><td><div class="actions">${actions}</div></td></tr>`;}
function apply(){render(filtered());}
async function load(){try{showMessage("Memuat artikel...");allArticles=await CMS.articles();updateStats(allArticles);loadCategories(allArticles);apply();showMessage(`${allArticles.length} artikel tersedia.`);}catch(e){console.error("Load articles error:",e);container.innerHTML='<div class="empty"><strong>Gagal memuat artikel</strong>Periksa koneksi Supabase dan Console.</div>';showMessage(e?.message||"Gagal memuat artikel.","error");}}
async function action(type,id){try{if(type==="delete"&&!confirm("Yakin ingin menghapus artikel ini?"))return;if(type==="delete")await CMS.deleteArticle(id);else if(type==="publish"){if(profile?.role!=="admin")throw new Error("Hanya Admin yang dapat publish artikel.");await CMS.changeStatus("articles",id,"published");}else if(type==="review")await CMS.changeStatus("articles",id,"review");else if(type==="archive")await CMS.changeStatus("articles",id,"archived");await load();showMessage("Aksi berhasil.","success");}catch(e){console.error("Article action error:",e);showMessage(e?.message||"Aksi gagal.","error");}}
container?.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(b)action(b.dataset.action,b.dataset.id);});
document.getElementById("status-tabs")?.addEventListener("click",e=>{const b=e.target.closest("[data-status]");if(!b)return;activeStatus=b.dataset.status;document.querySelectorAll(".status-tab").forEach(x=>x.classList.toggle("active",x===b));statusFilter.value="all";apply();});
$("search")?.addEventListener("input",apply);$("status-filter")?.addEventListener("change",apply);$("category-filter")?.addEventListener("change",apply);refreshButton?.addEventListener("click",load);$("clear-filters")?.addEventListener("click",()=>{searchInput.value="";statusFilter.value="all";categoryFilter.value="all";activeStatus="all";document.querySelectorAll(".status-tab").forEach(x=>x.classList.toggle("active",x.dataset.status==="all"));apply();});
newButton?.addEventListener("click",()=>{window.location.href="article-edit.html";});
logoutButton?.addEventListener("click",async()=>{try{await CMS.logout();}catch(e){console.error(e);showMessage(e?.message||"Gagal logout.","error");}});
async function init(){try{profile=await CMS.requireStaff();if(!profile)return;$("side-name").textContent=profile.full_name||profile.user?.email||"Pengguna";$("side-role").textContent=profile.role||"-";$("top-user").textContent=profile.full_name||profile.user?.email||"";await load();}catch(e){console.error("Articles init error:",e);showMessage(e?.message||"Gagal membuka halaman artikel.","error");}}
init();