(() => {
  'use strict';
  const FN='homepage-cover-upload';
  const API=(window.SUPABASE_URL||'https://roeckoabffhyctfkvbhw.supabase.co');
  const slots=[['hero_image_main','hero_image_main_key','main','Hero utama'],['hero_image_secondary','hero_image_secondary_key','secondary','Hero pendukung'],['hero_image_tertiary','hero_image_tertiary_key','tertiary','Hero ketiga'],['hero_overlay_image','hero_overlay_image_key','overlay','Background / overlay']];
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  async function token(){const a=await MandalaCMS.getCurrentAuth();if(a?.access_token)return a.access_token;if(a?.session?.access_token)return a.session.access_token;if(window.MandalaSupabase?.auth){const s=await window.MandalaSupabase.auth.getSession();return s?.data?.session?.access_token||null}return null}
  async function call(fd){const t=await token();if(!t)throw Error('Sesi admin tidak ditemukan. Silakan login kembali.');const r=await fetch(`${API}/functions/v1/${FN}`,{method:'POST',headers:{Authorization:`Bearer ${t}`},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||`Permintaan gagal (${r.status})`);return d}
  function card(url,key,slot,label){return `<div class="media-edit-card" data-slot="${slot}"><div class="media-preview">${url?`<img src="${esc(url)}" alt="${esc(label)}" onerror="this.style.display='none';this.parentElement.classList.add('broken')">`:'<span>Belum ada gambar</span>'}</div><div class="media-edit-body"><div class="media-edit-title">${esc(label)}</div><div class="media-edit-actions"><label class="btn btn-secondary media-upload-btn">Ganti gambar<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden></label>${key?'<button type="button" class="btn btn-ghost media-remove">Hapus</button>':''}</div><div class="media-edit-status">${key?'Tersimpan di Backblaze':'Belum menggunakan file Backblaze'}</div></div></div>`}
  window.initHomepageMedia=function(container,homepage,onSaved){container.innerHTML=`<div class="media-edit-grid">${slots.map(s=>card(homepage?.[s[0]],homepage?.[s[1]],s[2],s[3])).join('')}</div>`;slots.forEach(s=>{const el=container.querySelector(`[data-slot="${s[2]}"]`),input=el.querySelector('input[type=file]');input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const status=el.querySelector('.media-edit-status');status.textContent='Mengunggah ke Backblaze…';try{const fd=new FormData();fd.append('action','upload');fd.append('file',file);fd.append('slot',s[2]);if(homepage?.[s[1]])fd.append('oldKey',homepage[s[1]]);const d=await call(fd);await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:d.url,[s[1]]:d.key,updated_at:new Date().toISOString()});homepage[s[0]]=d.url;homepage[s[1]]=d.key;window.initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage)}catch(e){console.error(e);status.textContent=e.message||'Upload gagal.'}});const rm=el.querySelector('.media-remove');if(rm)rm.addEventListener('click',async()=>{if(!confirm(`Hapus ${s[3]} dari Beranda?`))return;try{const fd=new FormData();fd.append('action','delete');fd.append('key',homepage?.[s[1]]||'');await call(fd);await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:null,[s[1]]:null,updated_at:new Date().toISOString()});homepage[s[0]]=null;homepage[s[1]]=null;window.initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage)}catch(e){alert(e.message||'Gagal menghapus gambar.')}})})}
})();
