(() => {
  'use strict';
  const FN='homepage-cover-upload';
  const API=(window.SUPABASE_URL||'https://roeckoabffhyctfkvbhw.supabase.co').replace(/\/$/,'');
  const slots=[['hero_image_main','hero_image_main_key','main','Hero utama'],['hero_image_secondary','hero_image_secondary_key','secondary','Hero pendukung'],['hero_image_tertiary','hero_image_tertiary_key','tertiary','Hero ketiga'],['hero_overlay_image','hero_overlay_image_key','overlay','Background / overlay']];
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const imageUrl=(url,key)=>url||'';
  async function getAccessToken(){const db=await window.MandalaSupabase.getClient();const result=await db.auth.getSession();if(result?.error)throw result.error;const token=result?.data?.session?.access_token;if(!token)throw new Error('Sesi admin tidak ditemukan. Silakan login kembali.');return token}
  async function call(fd){const auth=await MandalaCMS.getCurrentAuth();if(!auth?.authenticated)throw new Error('Sesi admin tidak ditemukan. Silakan login kembali.');if(auth.role!=='admin')throw new Error('Akses upload gambar hanya untuk admin.');const token=await getAccessToken();const response=await fetch(`${API}/functions/v1/${FN}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||`Permintaan upload gagal (${response.status})`);return data}
  function card(url,key,slot,label){const src=imageUrl(url,key);const id=`img-${slot}-${Math.random().toString(36).slice(2)}`;const preview=src?`<img id="${id}" src="${esc(src)}" alt="${esc(label)}" loading="eager">`:'<span>Belum ada gambar</span>';return `<div class="media-edit-card" data-slot="${slot}"><div class="media-preview">${preview}</div><div class="media-edit-body"><div class="media-edit-title">${esc(label)}</div><div class="media-edit-actions"><label class="btn btn-secondary media-upload-btn">Ganti gambar<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden></label>${key?'<button type="button" class="btn btn-ghost media-remove">Hapus</button>':''}</div><div class="media-edit-status">${key?'Tersimpan di Backblaze':'Belum menggunakan file Backblaze'}</div></div></div>`}
  function bindImageFallback(container){container.querySelectorAll('.media-preview img').forEach(img=>{img.addEventListener('error',()=>{const preview=img.closest('.media-preview');if(!preview)return;img.remove();preview.classList.add('broken');const status=preview.parentElement?.querySelector('.media-edit-status');if(status)status.textContent='URL gambar tidak dapat dimuat.'},{once:true});});}
  window.initHomepageMedia=function(container,homepage,onSaved){container.innerHTML=`<div class="media-edit-grid">${slots.map(s=>card(homepage?.[s[0]],homepage?.[s[1]],s[2],s[3])).join('')}</div>`;bindImageFallback(container);slots.forEach(s=>{const el=container.querySelector(`[data-slot="${s[2]}"]`);if(!el)return;const input=el.querySelector('input[type=file]'),status=el.querySelector('.media-edit-status');input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;status.textContent='Mengunggah ke Backblaze…';try{const fd=new FormData();fd.append('action','upload');fd.append('file',file);fd.append('slot',s[2]);if(homepage?.[s[1]])fd.append('oldKey',homepage[s[1]]);const data=await call(fd);await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:data.url,[s[1]]:data.key,updated_at:new Date().toISOString()});homepage[s[0]]=data.url;homepage[s[1]]=data.key;window.initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage)}catch(error){console.error(error);status.textContent=error.message||'Upload gagal.';input.value=''}});const remove=el.querySelector('.media-remove');if(remove)remove.addEventListener('click',async()=>{if(!homepage?.[s[1]])return;if(!confirm(`Hapus ${s[3]} dari Beranda?`))return;try{const fd=new FormData();fd.append('action','delete');fd.append('key',homepage[s[1]]);await call(fd);await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:null,[s[1]]:null,updated_at:new Date().toISOString()});homepage[s[0]]=null;homepage[s[1]]=null;window.initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage)}catch(error){console.error(error);alert(error.message||'Gagal menghapus gambar.')}})})};
})();
