(() => {
  'use strict';
  const FN = 'homepage-cover-upload';
  const slots = [
    ['hero_image_main','hero_image_main_key','main','Hero utama'],
    ['hero_image_secondary','hero_image_secondary_key','secondary','Hero pendukung'],
    ['hero_image_tertiary','hero_image_tertiary_key','tertiary','Hero ketiga'],
    ['hero_overlay_image','hero_overlay_image_key','overlay','Background / overlay']
  ];
  const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  async function token(){ const a=await MandalaCMS.getCurrentAuth(); return a?.access_token || a?.session?.access_token || window.MandalaSupabase?.auth?.getSession ? (await window.MandalaSupabase.auth.getSession()).data.session?.access_token : null; }
  async function upload(file,slot,oldKey){ const t=await token(); if(!t) throw Error('Sesi admin tidak ditemukan.'); const fd=new FormData(); fd.append('action','upload'); fd.append('file',file); fd.append('slot',slot); if(oldKey) fd.append('oldKey',oldKey); const r=await fetch(`${window.SUPABASE_URL || 'https://roeckoabffhyctfkvbhw.supabase.co'}/functions/v1/${FN}`,{method:'POST',headers:{Authorization:`Bearer ${t}`},body:fd}); const d=await r.json().catch(()=>({})); if(!r.ok||!d.ok) throw Error(d.error||`Upload gagal (${r.status})`); return d; }
  function card(url,key,slot,label){ return `<div class="media-edit-card" data-slot="${slot}"><div class="media-preview">${url?`<img src="${esc(url)}" alt="${esc(label)}" onerror="this.style.display='none';this.parentElement.classList.add('broken')">`:'<span>Belum ada gambar</span>'}</div><div class="media-edit-body"><div class="media-edit-title">${esc(label)}</div><div class="media-edit-actions"><label class="btn btn-secondary media-upload-btn">Ganti gambar<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden></label>${key?'<button type="button" class="btn btn-ghost media-remove">Hapus</button>':''}</div><div class="media-edit-status">${key?'Tersimpan di Backblaze':'Gunakan file dari penyimpanan yang sudah ada'}</div></div></div>`; }
  window.initHomepageMedia = function(container, homepage, onSaved){ container.innerHTML = `<div class="media-edit-grid">${slots.map(s=>card(homepage?.[s[0]],homepage?.[s[1]],s[2],s[3])).join('')}</div>`; slots.forEach(s=>{const el=container.querySelector(`[data-slot="${s[2]}"]`);const input=el.querySelector('input[type=file]');input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const status=el.querySelector('.media-edit-status');status.textContent='Mengunggah…';try{const d=await upload(file,s[2],homepage?.[s[1]]);await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:d.url,[s[1]]:d.key,updated_at:new Date().toISOString()});homepage[s[0]]=d.url;homepage[s[1]]=d.key;initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage); }catch(e){console.error(e);status.textContent=e.message||'Upload gagal.'}});const rm=el.querySelector('.media-remove');if(rm)rm.addEventListener('click',async()=>{if(!confirm(`Hapus ${s[3]} dari Beranda?`))return;const t=await token();const fd=new FormData();fd.append('action','delete');fd.append('key',homepage?.[s[1]]||'');try{await fetch(`${window.SUPABASE_URL || 'https://roeckoabffhyctfkvbhw.supabase.co'}/functions/v1/${FN}`,{method:'POST',headers:{Authorization:`Bearer ${t}`},body:fd});await MandalaCMS.update('homepage_settings',homepage.id,{[s[0]]:null,[s[1]]:null,updated_at:new Date().toISOString()});homepage[s[0]]=null;homepage[s[1]]=null;initHomepageMedia(container,homepage,onSaved);if(onSaved)onSaved(homepage)}catch(e){alert(e.message||'Gagal menghapus gambar.')}});}); };
})();
