const $=id=>document.getElementById(id);
let auth=null,rows=[],activeStatus='all',activeType='all';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function typeBadge(x){const t=x.content_type==='audio'?'audio':'video';return `<span class="type-badge type-${t}">${t==='audio'?'🎧 Audio':'🎥 Video'}</span>`;}
function statusBadge(v){const s=String(v||'draft').toLowerCase();return `<span class="badge badge-${s}">${s==='published'?'Published':s==='review'?'Review':s==='archived'?'Arsip':'Draft'}</span>`;}
function imageFor(x){return x.cover_image_url?`<img class="podcast-thumb" src="${esc(x.cover_image_url)}" alt="">`:`<div class="podcast-fallback">${x.content_type==='audio'?'🎧 AUDIO':'🎥 VIDEO'}</div>`;}
function renderStats(){const total=rows.length,video=rows.filter(x=>x.content_type!=='audio').length,audio=rows.filter(x=>x.content_type==='audio').length,pub=rows.filter(x=>x.status==='published').length,featured=rows.filter(x=>x.featured).length;$('stat-total').textContent=total;$('stat-video').textContent=video;$('stat-audio').textContent=audio;$('stat-published').textContent=pub;$('stat-featured').textContent=featured;}
function filtered(){const q=($('search')?.value||'').trim().toLowerCase();return rows.filter(x=>{const t=x.content_type==='audio'?'audio':'video',s=String(x.status||'draft').toLowerCase(),text=[x.title,x.slug,x.description,x.categories?.name].join(' ').toLowerCase();return(!q||text.includes(q))&&(activeStatus==='all'||s===activeStatus)&&(activeType==='all'||t===activeType);});}
function render(){const data=filtered();$('result-count').textContent=`${data.length} podcast ditampilkan`;const box=$('podcasts-container');if(!data.length){box.innerHTML='<div class="empty"><strong>Tidak ada podcast.</strong>Coba ubah filter atau tambahkan podcast baru.</div>';return;}box.innerHTML=`<table class="table"><thead><tr><th>Podcast</th><th>Jenis</th><th>Status</th><th>Featured</th><th>Aksi</th></tr></thead><tbody>${data.map(x=>`<tr><td><div class="podcast-cell">${imageFor(x)}<div><div class="podcast-name">${esc(x.title)}</div><div class="podcast-sub">${esc(x.categories?.name||'Tanpa kategori')}</div></div></div></td><td>${typeBadge(x)}</td><td>${statusBadge(x.status)}</td><td>${x.featured?'<span class="featured-mark">★</span>':'—'}</td><td><div class="actions"><a class="action" href="podcast-edit.html?id=${encodeURIComponent(x.id)}">Edit</a>${auth?.role==='admin'?`<button class="action danger" type="button" data-del="${esc(x.id)}">Hapus</button>`:''}</div></td></tr>`).join('')}</tbody></table>`;box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(b.dataset.del));}
async function load(){const db=await MandalaSupabase.getClient();const {data,error}=await db.from('podcasts').select('id,title,slug,description,status,featured,content_type,cover_image_url,published_at,created_at,categories(name)').order('created_at',{ascending:false});if(error)throw error;rows=data||[];renderStats();render();}
async function remove(id){if(!confirm('Hapus podcast ini?'))return;const db=await MandalaSupabase.getClient();const {error}=await db.from('podcasts').delete().eq('id',id);if(error)showMessage(error.message,true);else{showMessage('Podcast berhasil dihapus.');await load();}}
function showMessage(text,error=false){const el=$('page-message');el.textContent=text;el.className='message '+(error?'error':'success');setTimeout(()=>{el.textContent='';el.className='message';},3500);}
async function init(){auth=await MandalaSupabase.auth.requireStaff({loginPage:'index.html',deniedPage:'dashboard.html'});if(!auth)return;const name=$('side-name'),role=$('side-role'),top=$('top-user');if(name)name.textContent=auth.full_name||auth.email||'Pengguna';if(role)role.textContent=auth.role||'';if(top)top.textContent=auth.email||'';const logout=$('logout-button');if(logout)logout.onclick=async()=>{await MandalaSupabase.auth.signOut();location.href='index.html';};$('search')?.addEventListener('input',render);$('type-filter')?.addEventListener('change',e=>{activeType=e.target.value;render();});$('status-filter')?.addEventListener('change',e=>{activeStatus=e.target.value;document.querySelectorAll('.status-tab').forEach(x=>x.classList.toggle('active',x.dataset.status===activeStatus));render();});$('clear-filters')?.addEventListener('click',()=>{$('search').value='';$('type-filter').value='all';$('status-filter').value='all';activeType='all';activeStatus='all';document.querySelectorAll('.status-tab').forEach(x=>x.classList.toggle('active',x.dataset.status==='all'));render();});$('refresh')?.addEventListener('click',load);document.querySelectorAll('.status-tab').forEach(b=>b.addEventListener('click',()=>{activeStatus=b.dataset.status;$('status-filter').value=activeStatus;document.querySelectorAll('.status-tab').forEach(x=>x.classList.toggle('active',x===b));render();}));document.querySelectorAll('[data-type-card]').forEach(b=>b.addEventListener('click',()=>{activeType=b.dataset.typeCard;$('type-filter').value=activeType;render();}));await load();}
init().catch(e=>{console.error(e);showMessage(e.message||'Gagal memuat podcast.',true);});