(() => {
  const $ = id => document.getElementById(id);
  let auth=null, editing=null, audioUrl=null;
  const id=new URLSearchParams(location.search).get('id');
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slugify=v=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
  const isStaff=()=>auth?.role==='admin'||auth?.role==='editor';
  const toast=(msg,error=false)=>{const e=$('toast');if(!e){console[error?'error':'log'](msg);return}e.textContent=msg;e.className='toast '+(error?'error':'');e.hidden=false;setTimeout(()=>e.hidden=true,3500)};
  const type=()=>document.querySelector('input[name="content_type"]:checked')?.value||'video';
  function youtubeId(v=''){v=v.trim();if(/^[A-Za-z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v),h=u.hostname.replace(/^www\./,'').toLowerCase();if(h==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||'';if(h==='youtube.com'||h==='m.youtube.com'||h==='music.youtube.com')return u.searchParams.get('v')||u.pathname.match(/\/(?:embed|shorts|live)\/([A-Za-z0-9_-]{11})/)?.[1]||''}catch(_){}return ''}
  function youtubeThumb(){const y=youtubeId($('youtube_video_id')?.value||'')||youtubeId($('youtube_url')?.value||'');return y?`https://i.ytimg.com/vi/${encodeURIComponent(y)}/hqdefault.jpg`:''}
  function coverUrl(v=''){const s=String(v||'').trim();if(!s)return '';if(/playlist-covers\//i.test(s))return `https://roeckoabffhyctfkvbhw.supabase.co/functions/v1/playlist-cover-proxy?url=${encodeURIComponent(s)}`;return s}
  function renderCover(){const box=$('cover-preview'),img=$('cover-preview-img'),fallback=$('cover-preview-fallback');if(!box||!img||!fallback)return;let src=type()==='video'?youtubeThumb():coverUrl($('cover_image_url')?.value||'');if(!src){box.hidden=true;return}box.hidden=false;fallback.hidden=true;img.hidden=false;img.src=src;img.onload=()=>{img.hidden=false;fallback.hidden=true};img.onerror=()=>{img.hidden=true;fallback.hidden=false;fallback.textContent='Thumbnail tidak dapat dimuat.'}}
  function toggleType(){const video=type()==='video';$('videoFields')?.classList.toggle('show',video);$('audioFields')?.classList.toggle('show',!video);renderCover()}
  async function loadCategories(){const db=await MandalaSupabase.getClient();const{data,error}=await db.from('categories').select('id,name').eq('is_active',true).order('sort_order').order('name');if(error)throw error;const e=$('category_id');if(e)e.innerHTML='<option value="">Tanpa kategori</option>'+(data||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}
  async function loadPodcast(){if(!id){renderCover();return}const db=await MandalaSupabase.getClient();const{data,error}=await db.from('podcasts').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Podcast tidak ditemukan.');editing=data;audioUrl=data.audio_url||null;$('title').value=data.title||'';$('slug').value=data.slug||'';$('description').value=data.description||'';$('youtube_url').value=data.youtube_url||'';$('youtube_video_id').value=data.youtube_video_id||youtubeId(data.youtube_url||'');$('cover_image_url').value=data.cover_image_url||'';$('category_id').value=data.category_id||'';$('featured').checked=!!data.featured;$('status').value=data.status||'draft';const te=document.getElementById(data.content_type==='audio'?'type_audio':'type_video');if(te)te.checked=true;toggleType();if(audioUrl){$('currentAudio').hidden=false;$('currentAudio').innerHTML=`Audio saat ini tersimpan: <code>${esc(audioUrl)}</code>`}}
  function getDuration(file){return new Promise(resolve=>{if(!file)return resolve(null);const a=document.createElement('audio');a.preload='metadata';a.onloadedmetadata=()=>{URL.revokeObjectURL(a.src);resolve(Number.isFinite(a.duration)?Math.round(a.duration):null)};a.onerror=()=>resolve(null);a.src=URL.createObjectURL(file)})}
  async function uploadAudio(file){if(!file)return audioUrl;if(file.size>50*1024*1024)throw new Error('File audio maksimal 50 MB.');if(!file.type.startsWith('audio/'))throw new Error('File harus berupa audio.');const db=await MandalaSupabase.getClient(),form=new FormData();form.append('action','upload');form.append('file',file,file.name);$('uploadProgress').style.display='block';$('uploadProgress').querySelector('i').style.width='20%';const{data,error}=await db.functions.invoke('podcast-storage',{body:form});if(error){let d='';try{if(error.context instanceof Response){const b=await error.context.clone().json();d=b?.error||''}}catch(_){}throw new Error(d||error.message||'Upload ke Backblaze gagal.')}if(!data?.ok||!data?.key)throw new Error(data?.error||'Upload ke Backblaze gagal.');$('uploadProgress').querySelector('i').style.width='100%';return data.key}
  async function save(){const title=$('title').value.trim();if(!title)return toast('Judul podcast wajib diisi.',true);const content_type=type(),status=$('status').value;if(!isStaff())return toast('Akses CMS tidak valid.',true);const file=$('audio_file').files[0];if(content_type==='audio'&&!file&&!audioUrl)return toast('Upload file audio terlebih dahulu.',true);const yt=content_type==='video'?(youtubeId($('youtube_video_id').value)||youtubeId($('youtube_url').value)):null;if(content_type==='video'&&!yt)return toast('Masukkan YouTube URL atau Video ID yang valid.',true);if(content_type==='audio'&&file)audioUrl=await uploadAudio(file);const payload={title,slug:($('slug').value.trim()||slugify(title)),description:$('description').value.trim()||null,content_type,youtube_url:content_type==='video'?($('youtube_url').value.trim()||null):null,youtube_video_id:yt,audio_url:content_type==='audio'?(audioUrl||null):null,audio_duration:content_type==='audio'&&file?await getDuration(file):(editing?.audio_duration||null),cover_image_url:content_type==='video'?(youtubeThumb()||null):(($('cover_image_url').value.trim()||null)),category_id:$('category_id').value||null,featured:$('featured').checked,status};if(status==='published'&&!editing?.published_at)payload.published_at=new Date().toISOString();else if(status!=='published')payload.published_at=editing?.published_at||null;if(editing)payload.updated_at=new Date().toISOString();else payload.author_id=auth.user.id;const db=await MandalaSupabase.getClient(),result=editing?await db.from('podcasts').update(payload).eq('id',id):await db.from('podcasts').insert(payload);if(result.error)throw result.error;toast('Podcast berhasil disimpan.');setTimeout(()=>location.href='podcasts.html',500)}
  async function init(){auth=await MandalaSupabase.auth.requireStaff({loginPage:'index.html',deniedPage:'dashboard.html'});if(!auth)return;const role=$('role');if(role)role.textContent=auth.role==='admin'?'ADMIN':'EDITOR';await loadCategories();await loadPodcast();document.querySelectorAll('input[name="content_type"]').forEach(e=>e.addEventListener('change',toggleType));$('youtube_url')?.addEventListener('input',()=>{const y=youtubeId($('youtube_url').value);if(y)$('youtube_video_id').value=y;renderCover()});$('youtube_video_id')?.addEventListener('input',renderCover);$('cover_image_url')?.addEventListener('input',renderCover);$('audio_file')?.addEventListener('change',async()=>{const f=$('audio_file').files[0];if(!f){$('audioInfo').textContent='';return}const d=await getDuration(f);$('audioInfo').textContent=`${f.name} · ${(f.size/1048576).toFixed(1)} MB${d?` · ${Math.floor(d/60)}:${String(d%60).padStart(2,'0')}`:''}`});$('slug')?.addEventListener('input',()=>$('slug').dataset.manual='1');$('title')?.addEventListener('input',()=>{if(!$('slug').dataset.manual&&!id)$('slug').value=slugify($('title').value)});$('save')?.addEventListener('click',()=>save().catch(e=>{console.error(e);toast(e.message||'Gagal menyimpan podcast.',true)}));$('cancel')?.addEventListener('click',()=>location.href='podcasts.html');$('logout')?.addEventListener('click',async()=>{await MandalaSupabase.auth.signOut();location.href='index.html'})}
  init().catch(e=>{console.error(e);toast(e.message||'Gagal memuat podcast.',true)})
})();