const $=id=>document.getElementById(id);
let auth=null,rows=[],activeStatus='all',activeType='all',featuredOnly=false;
const COVER_PROXY='https://roeckoabffhyctfkvbhw.supabase.co/functions/v1/playlist-cover-proxy';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function youtubeId(v=''){v=String(v||'').trim();if(/^[A-Za-z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v),h=u.hostname.replace(/^www\./,'').toLowerCase();if(h==='youtu.be')return u.pathname.split('/').filter(Boolean)[0]||'';if(['youtube.com','m.youtube.com','music.youtube.com'].includes(h))return u.searchParams.get('v')||(u.pathname.match(/\/(?:embed|shorts|live)\/([A-Za-z0-9_-]{11})/)||[])[1]||''}catch(e){}return ''}
function youtubeThumb(x){const id=youtubeId(x.youtube_video_id)||youtubeId(x.youtube_url)||youtubeId(x.cover_image_url);return id?`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:''}
function coverUrl(v){const s=String(v||'').trim();if(!s)return '';if(/playlist-covers\//i.test(s))return `${COVER_PROXY}?url=${encodeURIComponent(s)}`;return s;}
function typeBadge(x){const t=x.content_type==='audio'?'audio':'video';return `<span class="type-badge type-${t}">${t==='audio'?'🎧 Audio':'🎥 Video'}</span>`;}
function statusBadge(v){const s=String(v||'draft').toLowerCase();return `<span class="badge badge-${s}">${s==='published'?'Published':s==='review'?'Review':s==='archived'?'Arsip':'Draft'}</span>`;}
function imageFor(x){const src=x.content_type==='audio'?coverUrl(x.cover_image_url):youtubeThumb(x)||coverUrl(x.cover_image_url);if(src)return `<img class="podcast-thumb" src="${esc(src)}" alt="${esc(x.title||'')}" loading="eager" decoding="async" referrerpolicy="no-referrer" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`+`<div class="podcast-fallback" style="display:none">${x.content_type==='audio'?'🎧':'🎥'}</div>`;return `<div class="podcast-fallback">${x.content_type==='audio'?'🎧':'🎥'}</div>`;}
function renderStats(){const total=rows.length,video=rows.filter(x=>x.content_type!=='audio').length,audio=rows.filter(x=>x.content_type==='audio').length,pub=rows.filter(x=>x.status==='published').length,featured=rows.filter(x=>x.featured).length;$('stat-total').textContent=total;$('stat-video').textContent=video;$('stat-audio').textContent=audio;$('stat-published').textContent=pub;$('stat-featured').textContent=featured;}
function filtered(){const q=($('search')?.value||'').trim().toLowerCase();return rows.filter(x=>{const t=x.content_type==='audio'?'audio':'video',s=String(x.status||'draft').toLowerCase(),text=[x.title,x.slug,x.description,x.categories?.name].join(' ').toLowerCase();return(!q||text.includes(q))&&(activeStatus==='all'||s===activeStatus)&&(activeType==='all'||t===activeType)&&(!featuredOnly||!!x.featured);});}
function render(){const data=filtered();$('result-count').textContent=`${data.length} podcast${data.length===1?'':'s'} ditampilkan`;const box=$('podcasts-container');if(!data.length){box.innerHTML='<div class="empty"><strong>Tidak ada podcast.</strong>Coba ubah filter atau tambahkan podcast baru.</div>';return;}box.innerHTML=`<table class="table"><thead><tr><th>Podcast</th><th>Jenis</th><th>Status</th><th>Publikasi</th><th>Aksi</th></tr></thead><tbody>${data.map(x=>`<tr><td><div class="podcast-cell">${imageFor(x)}<div><div class="podcast-name">${esc(x.title)}${x.featured?'<span class="featured-mark">★</span>':''}</div><div class="podcast-sub">${esc(x.categories?.name||'Tanpa kategori')}</div></div></div></td><td>${typeBadge(x)}</td><td>${statusBadge(x.status)}</td><td>${x.published_at?new Date(x.published_at).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'—'}</td><td><div class="actions"><a class="action" href="podcast-edit.html?id=${encodeURIComponent(x.id)}">Edit</a>${auth?.role==='admin'?`<button class="action danger" type="button" data-del="${esc(x.id)}">Hapus</button>`:''}</div></td></tr>`).join('')}</tbody></table>`;box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(b.dataset.del));}
async function load(){const db=await MandalaSupabase.getClient();const {data,error}=await db.from('podcasts').select('id,title,slug,description,status,featured,content_type,cover_image_url,youtube_url,youtube_video_id,published_at,created_at,categories(name)').order('created_at',{ascending:false});if(error)throw error;rows=data||[];renderStats();render();}
async function remove(id){if(!confirm('Hapus podcast ini?'))return;const db=await MandalaSupabase.getClient();const {error}=await db.from('podcasts').delete().eq('id',id);if(error)showMessage(error.message,true);else{showMessage('Podcast berhasil dihapus.');await load();}}
function showMessage(text,error=false){const el=$('page-message');el.textContent=text;el.className='message '+(error?'error':'success');setTimeout(()=>{el.textContent='';el.className='message';},3500);}
function syncTabs(){document.querySelectorAll('.status-tab').forEach(x=>x.classList.toggle('active',!featuredOnly&&x.dataset.status===activeStatus));}
async function init(){auth=await MandalaSupabase.auth.requireStaff({loginPage:'index.html',deniedPage:'dashboard.html'});if(!auth)return;const name=$('side-name'),role=$('side-role'),top=$('top-user');if(name)name.textContent=auth.full_name||auth.email||'Pengguna';if(role)role.textContent=auth.role||'';if(top)top.textContent=auth.email||'';const logout=$('logout-button');if(logout)logout.onclick=async()=>{await MandalaSupabase.auth.signOut();location.href='index.html';};$('search')?.addEventListener('input',render);$('type-filter')?.addEventListener('change',e=>{activeType=e.target.value;featuredOnly=false;render();});$('status-filter')?.addEventListener('change',e=>{activeStatus=e.target.value;featuredOnly=false;syncTabs();render();});$('clear-filters')?.addEventListener('click',()=>{$('search').value='';$('type-filter').value='all';$('status-filter').value='all';activeType='all';activeStatus='all';featuredOnly=false;syncTabs();render();});$('refresh')?.addEventListener('click',load);document.querySelectorAll('.status-tab').forEach(b=>b.addEventListener('click',()=>{activeStatus=b.dataset.status;activeType='all';featuredOnly=false;$('status-filter').value=activeStatus;$('type-filter').value='all';syncTabs();render();}));document.querySelectorAll('[data-type-card]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.typeCard;if(v==='featured'){featuredOnly=true;activeStatus='all';activeType='all';$('status-filter').value='all';$('type-filter').value='all';}else{featuredOnly=false;activeType=v==='all'?'all':v;activeStatus='all';$('type-filter').value=activeType;$('status-filter').value='all';}syncTabs();render();}));await load();}
init().catch(e=>{console.error(e);showMessage(e.message||'Gagal memuat podcast.',true);});