(() => {
  const $ = (id) => document.getElementById(id);
  let auth = null;
  const id = new URLSearchParams(location.search).get('id');
  let editing = null;
  let audioUrl = null;
  const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slugify = (v='') => v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');
  const isAdmin = () => auth?.role === 'admin';
  const toast = (msg,error=false) => { const el=$('toast'); if(!el){console[error?'error':'log'](msg);return;} el.textContent=msg; el.className='toast '+(error?'error':''); el.hidden=false; setTimeout(()=>el.hidden=true,3500); };
  const type = () => document.querySelector('input[name="content_type"]:checked')?.value || 'video';
  function toggleType(){ const video=type()==='video'; $('videoFields')?.classList.toggle('show',video); $('audioFields')?.classList.toggle('show',!video); }
  function youtubeId(v=''){const s=v.trim();if(/^[A-Za-z0-9_-]{11}$/.test(s))return s;try{const u=new URL(s),h=u.hostname.replace('www.','').toLowerCase();if(h==='youtu.be')return u.pathname.slice(1).split('/')[0];if(h==='youtube.com'||h==='m.youtube.com')return u.searchParams.get('v')||u.pathname.match(/\/(?:embed|shorts)\/([A-Za-z0-9_-]{11})/)?.[1]||''}catch(e){}return '';}
  async function loadCategories(){const db=await MandalaSupabase.getClient();const{data,error}=await db.from('categories').select('id,name').eq('is_active',true).order('sort_order').order('name');if(error)throw error;const el=$('category_id');if(!el)return;el.innerHTML='<option value="">Tanpa kategori</option>'+(data||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');}
  async function loadPodcast(){if(!id)return;const db=await MandalaSupabase.getClient();const{data,error}=await db.from('podcasts').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Podcast tidak ditemukan.');editing=data;audioUrl=data.audio_url||null;$('title').value=data.title||'';$('slug').value=data.slug||'';$('description').value=data.description||'';$('youtube_url').value=data.youtube_url||'';$('youtube_video_id').value=data.youtube_video_id||'';$('cover_image_url').value=data.cover_image_url||'';$('category_id').value=data.category_id||'';$('featured').checked=!!data.featured;$('status').value=data.status||'draft';const typeEl=document.getElementById(data.content_type==='audio'?'type_audio':'type_video');if(typeEl)typeEl.checked=true;toggleType();if(audioUrl){$('currentAudio').hidden=false;$('currentAudio').innerHTML=`Audio saat ini: <a href="${esc(audioUrl)}" target="_blank" rel="noopener">Buka file</a>`;}if(!isAdmin()){$('status').querySelector('option[value="published"]').disabled=true;if(data.status==='published')document.querySelectorAll('input,select,textarea').forEach(e=>e.disabled=true);}}
  function getDuration(file){return new Promise(resolve=>{if(!file)return resolve(null);const a=document.createElement('audio');a.preload='metadata';a.onloadedmetadata=()=>{URL.revokeObjectURL(a.src);resolve(Number.isFinite(a.duration)?Math.round(a.duration):null)};a.onerror=()=>resolve(null);a.src=URL.createObjectURL(file);});}
  async function uploadAudio(file){if(!file)return audioUrl;if(file.size>50*1024*1024)throw new Error('File audio maksimal 50 MB.');if(!file.type.startsWith('audio/'))throw new Error('File harus berupa audio.');const db=await MandalaSupabase.getClient();const ext=(file.name.split('.').pop()||'mp3').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`podcasts/${crypto.randomUUID()}.${ext}`;$('uploadProgress').style.display='block';$('uploadProgress').querySelector('i').style.width='20%';const{error}=await db.storage.from('podcast-audio').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;$('uploadProgress').querySelector('i').style.width='100%';return db.storage.from('podcast-audio').getPublicUrl(path).data.publicUrl;}
  async function save(){const title=$('title').value.trim();if(!title)return toast('Judul podcast wajib diisi.',true);const content_type=type(),status=$('status').value;if(!isAdmin()&&status==='published')return toast('Editor tidak dapat publish podcast.',true);if(!isAdmin()&&editing?.status==='published')return toast('Podcast yang sudah published hanya dapat diubah oleh Admin.',true);const file=$('audio_file').files[0];if(content_type==='audio'&&!file&&!audioUrl)return toast('Upload file audio terlebih dahulu.',true);if(content_type==='video'&&!$('youtube_url').value.trim()&&!youtubeId($('youtube_video_id').value))return toast('Masukkan YouTube URL atau Video ID.',true);if(content_type==='audio'&&file)audioUrl=await uploadAudio(file);const yt=content_type==='video'?($('youtube_video_id').value.trim()||youtubeId($('youtube_url').value)):null;const payload={title,slug:($('slug').value.trim()||slugify(title)),description:$('description').value.trim()||null,content_type,youtube_url:content_type==='video'?($('youtube_url').value.trim()||null):null,youtube_video_id:yt||null,audio_url:content_type==='audio'?(audioUrl||null):null,audio_duration:content_type==='audio'&&file?await getDuration(file):(editing?.audio_duration||null),cover_image_url:$('cover_image_url').value.trim()||null,category_id:$('category_id').value||null,featured:$('featured').checked,status};if(status==='published'&&!editing?.published_at)payload.published_at=new Date().toISOString();else if(status!=='published')payload.published_at=editing?.published_at||null;if(editing)payload.updated_at=new Date().toISOString();else payload.author_id=auth.user.id;const db=await MandalaSupabase.getClient();const result=editing?await db.from('podcasts').update(payload).eq('id',id):await db.from('podcasts').insert(payload);if(result.error)throw result.error;toast('Podcast berhasil disimpan.');setTimeout(()=>location.href='podcasts.html',500);}
  async function init(){auth=await MandalaSupabase.auth.requireStaff({loginPage:'index.html',deniedPage:'dashboard.html'});if(!auth)return;const role=$('role');if(role)role.textContent=auth.role==='admin'?'ADMIN':'EDITOR';await loadCategories();await loadPodcast();toggleType();document.querySelectorAll('input[name="content_type"]').forEach(e=>e.addEventListener('change',toggleType));$('audio_file')?.addEventListener('change',async()=>{const f=$('audio_file').files[0];if(!f){$('audioInfo').textContent='';return;}const d=await getDuration(f);$('audioInfo').textContent=`${f.name} · ${(f.size/1048576).toFixed(1)} MB${d?` · ${Math.floor(d/60)}:${String(d%60).padStart(2,'0')}`:''}`;});$('slug')?.addEventListener('input',()=>$('slug').dataset.manual='1');$('title')?.addEventListener('input',()=>{if(!$('slug').dataset.manual&&!id)$('slug').value=slugify($('title').value);});$('youtube_url')?.addEventListener('blur',()=>{if(type()==='video'&&!$('youtube_video_id').value)$('youtube_video_id').value=youtubeId($('youtube_url').value);});$('save')?.addEventListener('click',()=>save().catch(e=>{console.error(e);toast(e.message||'Gagal menyimpan podcast.',true)}));$('cancel')?.addEventListener('click',()=>location.href='podcasts.html');$('logout')?.addEventListener('click',async()=>{await MandalaSupabase.auth.signOut();location.href='index.html';});}
  init().catch(e=>{console.error(e);toast(e.message||'Gagal memuat.',true)});
})();