import { getVideos,getCategories,deleteVideo,getCurrentAuth,logout } from "./cms-service.js";
const $=(s,r=document)=>r.querySelector(s),container=$("#videos-container"),message=$("#page-message"),permissionNote=$("#permission-note");let videos=[],categories=[],auth=null,currentStatus="all",loading=false;
const FALLBACK_THUMBNAIL="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 360"><rect width="640" height="360" fill="#edf1f5"/><text x="320" y="170" text-anchor="middle" font-family="Arial" font-size="30" font-weight="700" fill="#082d56">MANDALA</text><text x="320" y="205" text-anchor="middle" font-family="Arial" font-size="16" fill="#718091">CHANNEL · VIDEO</text></svg>');
const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const date=v=>{if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("id-ID",{day:"2-digit",month:"short",year:"numeric"})};
const label=v=>({draft:"Draft",review:"Review",published:"Published",archived:"Arsip"}[v]||v||"-");
const vidId=v=>{if(v?.youtube_video_id)return v.youtube_video_id;const m=String(v?.youtube_url||"").match(/(?:v=|youtu\.be\/|youtube\.com\/(?:embed|shorts)\/)([A-Za-z0-9_-]{11})/);return m?.[1]||""};
const thumb=v=>v?.thumbnail_url||((id=vidId(v))?`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:FALLBACK_THUMBNAIL);
function msg(t="",type=""){if(message){message.textContent=t;message.className=`message ${type}`.trim()}}
function stats(){const c=s=>videos.filter(v=>v.status===s).length;$("#stat-total").textContent=videos.length;$("#stat-draft").textContent=c("draft");$("#stat-review").textContent=c("review");$("#stat-published").textContent=c("published");$("#stat-archived").textContent=c("archived");$("#stat-featured").textContent=videos.filter(v=>v.featured===true).length}
function categoriesUI(){const s=$("#category-filter");if(!s)return;s.innerHTML='<option value="all">Semua kategori</option>'+categories.filter(c=>c?.is_active!==false).map(c=>`<option value="${esc(c.id)}">${esc(c.name||"Tanpa nama")}</option>`).join("")}
function statusUI(){const s=$("#status-filter");if(s)s.value=["all","draft","review","published","archived"].includes(currentStatus)?currentStatus:"all";document.querySelectorAll(".status-tab").forEach(b=>b.classList.toggle("active",b.dataset.status===currentStatus))}
function setStatus(s="all"){currentStatus=s;statusUI();render()}
function filtered(){const q=$("#search")?.value.trim().toLowerCase()||"",cat=$("#category-filter")?.value||"all";return videos.filter(v=>{const text=[v.title,v.slug,v.youtube_video_id,v.youtube_url,v.description].filter(Boolean).join(" ").toLowerCase();return(!q||text.includes(q))&&(currentStatus==="all"||currentStatus==="featured"||v.status===currentStatus)&&(currentStatus!=="featured"||v.featured===true)&&(cat==="all"||String(v.category_id||"")===String(cat))})}
function row(v){const c=categories.find(x=>String(x.id)===String(v.category_id)),id=vidId(v),status=v.status||"draft",title=v.title||"Tanpa judul";const canDelete=auth?.role==="admin";const del=canDelete?`<button class="action danger" type="button" data-action="delete" data-id="${esc(v.id)}">Hapus</button>`:"";return `<tr><td><div class="video-cell"><div class="video-thumb-wrap"><img class="thumb" src="${esc(thumb(v))}" alt="${esc(title)}" loading="lazy" onerror="this.onerror=null;this.src='${FALLBACK_THUMBNAIL}'></div><div><div class="video-name">${esc(title)}</div><div class="video-sub">${id?`YouTube ID: ${esc(id)}`:"YouTube ID belum tersedia"}${v.featured?'<span class="featured-mark">★ Unggulan</span>':""}</div></div></div></td><td>${esc(c?.name||"Tanpa kategori")}</td><td><span class="badge badge-${["draft","review","published","archived"].includes(status)?status:"draft"}">${esc(label(status))}</span></td><td>${date(v.created_at)}</td><td>${v.published_at?date(v.published_at):"-"}</td><td><div class="actions"><a class="action" href="video-edit.html?id=${encodeURIComponent(v.id)}">Edit</a>${v.youtube_url?`<a class="action" href="${esc(v.youtube_url)}" target="_blank" rel="noopener noreferrer">YouTube ↗</a>`:""}${del}</div></td></tr>`}
function render(){if(!container)return;const rows=filtered(),rc=$("#result-count");if(rc)rc.textContent=`${rows.length} dari ${videos.length} video`;container.innerHTML=rows.length?`<table class="table"><thead><tr><th>Video</th><th>Kategori</th><th>Status</th><th>Dibuat</th><th>Publikasi</th><th>Aksi</th></tr></thead><tbody>${rows.map(row).join("")}</tbody></table>`:'<div class="empty"><strong>Tidak ada video</strong>Tidak ada video yang sesuai dengan filter saat ini.</div>'}
function roleUI(){if(!permissionNote)return;if(auth?.role==="editor"){permissionNote.textContent="Mode Editor: dapat membuat dan mengelola konten. Publish dan hapus video hanya oleh Admin.";permissionNote.style.display="block"}else if(auth?.role==="admin"){permissionNote.textContent="Mode Admin: seluruh status video dapat dikelola.";permissionNote.style.display="block"}else permissionNote.style.display="none"}
async function load(){if(loading)return;loading=true;const refresh=$("#refresh");if(refresh){refresh.disabled=true;refresh.textContent="Memuat..."}try{auth=await getCurrentAuth();if(!auth?.authenticated){location.replace("login.html?next=videos.html");return}if(!["admin","editor"].includes(auth.role)){location.replace("index.html");return}$("#side-name").textContent=auth.profile?.full_name||auth.user?.email||"Pengguna";$("#side-role").textContent=auth.role||"-";$("#top-user").textContent=auth.profile?.full_name||auth.user?.email||"";roleUI();const [vr,cr]=await Promise.all([getVideos(),getCategories()]);videos=Array.isArray(vr)?vr:[];categories=Array.isArray(cr)?cr:[];stats();categoriesUI();statusUI();render();msg("")}catch(e){console.error(e);msg(e?.message||"Gagal memuat video.","error");if(container)container.innerHTML=`<div class="empty"><strong>Gagal memuat video</strong>${esc(e?.message||"Periksa koneksi Supabase.")}</div>`}finally{loading=false;if(refresh){refresh.disabled=false;refresh.textContent="↻ Refresh"}}}
async function del(id,b){const v=videos.find(x=>String(x.id)===String(id));if(!v||auth?.role!=="admin"){msg("Hanya Admin yang dapat menghapus video.","error");return}if(!confirm(`Hapus video “${v.title||"Tanpa judul"}”?`))return;b.disabled=true;try{await deleteVideo(id);videos=videos.filter(x=>String(x.id)!==String(id));stats();render();msg("Video berhasil dihapus.","success")}catch(e){b.disabled=false;msg(e?.message||"Gagal menghapus video.","error")}}
function reset(){$("#search")&&($("#search").value="");$("#category-filter")&&($("#category-filter").value="all");setStatus("all")}
$("#search")?.addEventListener("input",render);$("#status-filter")?.addEventListener("change",e=>setStatus(e.target.value||"all"));$("#category-filter")?.addEventListener("change",render);$("#clear-filters")?.addEventListener("click",e=>{e.preventDefault();reset()});$("#refresh")?.addEventListener("click",e=>{e.preventDefault();load()});document.querySelectorAll(".status-tab,[data-status-card]").forEach(b=>b.addEventListener("click",()=>setStatus(b.dataset.status||b.dataset.statusCard||"all")));container?.addEventListener("click",e=>{const b=e.target.closest('[data-action="delete"]');if(b)del(b.dataset.id,b)});document.querySelectorAll("#logout,#logout-button").forEach(b=>b.addEventListener("click",()=>logout()));load();