import { getCurrentAuth, getCategories, getVideo, createVideo, updateVideo, deleteVideo, logout } from "./cms-service.js";

const $=s=>document.querySelector(s);
const form=$("#video-form"), titleInput=$("#judul_video"), slugInput=$("#slug"), youtubeUrlInput=$("#youtube_url"), youtubeIdInput=$("#youtube_video_id"), thumbnailInput=$("#thumbnail_url"), descriptionInput=$("#deskripsi"), categoryInput=$("#kategori"), featuredInput=$("#is_featured"), statusInput=$("#status"), message=$("#form-message"), logoutButton=$("#logout");
const saveButton=$("#simpan"), draftButton=$("#simpan_draft"), reviewButton=$("#kirim_review"), publishButton=$("#publish"), archiveButton=$("#arsipkan");
let auth=null,currentVideo=null,slugManual=false;

function show(text,type=""){if(!message)return;message.textContent=text||"";message.className=`form-message message ${type}`;}
function slug(text){return String(text||"").toLowerCase().trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");}
function youtubeId(value){const s=String(value||"").trim();if(/^[A-Za-z0-9_-]{11}$/.test(s))return s;try{const u=new URL(s),h=u.hostname.toLowerCase().replace(/^www\./,"");if(h==="youtu.be")return u.pathname.split("/")[1]||"";if(h==="youtube.com"||h==="m.youtube.com")return u.searchParams.get("v")||u.pathname.match(/\/(?:shorts|embed)\/([A-Za-z0-9_-]{11})/)?.[1]||"";}catch{}return "";}
function updateYoutube(){const id=youtubeId(youtubeUrlInput.value);youtubeIdInput.value=id;if(id&&!thumbnailInput.value.trim())thumbnailInput.value=`https://i.ytimg.com/vi/${id}/hqdefault.jpg`;updatePreview();}
function updatePreview(){const id=youtubeIdInput.value;$("#preview-title")&&( $("#preview-title").textContent=titleInput.value.trim()||"Judul video");$("#preview-id")&&($("#preview-id").textContent=`YouTube ID: ${id||"—"}`);const img=$("#preview-image");if(img){img.src=id?`https://i.ytimg.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:"";img.style.visibility=id?"visible":"hidden";}}
function canPublish(){return auth?.role==="admin";}
function setButtons(){const admin=canPublish();publishButton.disabled=!admin;publishButton.title=admin?"":"Hanya Admin";if(auth?.role==="editor"&&currentVideo?.status==="published"){[saveButton,draftButton,reviewButton,archiveButton].forEach(b=>b.disabled=true);show("Video published dikunci untuk Editor. Hanya Admin yang dapat mengubahnya.","warning");}}

async function loadAuth(){auth=await getCurrentAuth();if(!auth?.authenticated){window.location.href="index.html";return false;}$("#side-name")&&($("#side-name").textContent=auth.profile?.full_name||auth.user?.email||"Pengguna");$("#side-role")&&($("#side-role").textContent=auth.role||"-");$("#top-user")&&($("#top-user").textContent=auth.profile?.full_name||auth.user?.email||"");if(auth.role!=="admin"&&auth.role!=="editor")throw new Error("Anda tidak memiliki akses ke editor video.");return true;}

async function loadCategories(selected=null){const data=await getCategories();categoryInput.innerHTML='<option value="">-- Pilih Kategori --</option>';data.forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=c.name;categoryInput.appendChild(o);});if(selected)categoryInput.value=selected;}

async function loadExisting(id){currentVideo=await getVideo(id);if(!currentVideo)throw new Error("Video tidak ditemukan.");titleInput.value=currentVideo.title||"";slugInput.value=currentVideo.slug||"";slugManual=true;youtubeUrlInput.value=currentVideo.youtube_url||"";youtubeIdInput.value=currentVideo.youtube_video_id||youtubeId(currentVideo.youtube_url);thumbnailInput.value=currentVideo.thumbnail_url||"";descriptionInput.value=currentVideo.description||"";featuredInput.checked=currentVideo.featured===true;statusInput.value=currentVideo.status||"draft";await loadCategories(currentVideo.category_id);$("#page-title")&&($("#page-title").textContent="Edit Video");$("#top-title")&&($("#top-title").textContent="Edit Video");$("#page-subtitle")&&($("#page-subtitle").textContent="Perbarui video tanpa mengubah alur publikasi.");updateYoutube();setButtons();if(auth.role==="admin")$("#hapus")&&($("#hapus").style.display="inline-flex");show("Video berhasil dimuat.","success");}

function payload(status){const title=titleInput.value.trim(),url=youtubeUrlInput.value.trim(),id=youtubeId(url);if(!title)throw new Error("Judul video wajib diisi.");if(!id)throw new Error("Masukkan URL YouTube yang valid.");const s=slugInput.value.trim()||slug(title);if(!s)throw new Error("Slug video wajib diisi.");return{title,slug:s,youtube_url:url,youtube_video_id:id,thumbnail_url:thumbnailInput.value.trim()||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`,description:descriptionInput.value.trim()||null,category_id:categoryInput.value||null,featured:featuredInput.checked,status,author_id:auth.user.id};}

async function save(status){try{if(status==="published"&&!canPublish())throw new Error("Hanya Admin yang dapat publish.");if(auth.role==="editor"&&currentVideo?.status==="published")throw new Error("Editor tidak dapat mengubah video yang sudah published.");[saveButton,draftButton,reviewButton,publishButton,archiveButton].forEach(b=>b.disabled=true);show("Menyimpan...");const p=payload(status);currentVideo=currentVideo?.id?await updateVideo(currentVideo.id,p):await createVideo(p);statusInput.value=currentVideo.status||status;const u=new URL(location.href);u.searchParams.set("id",currentVideo.id);history.replaceState({},"",u);if(!currentVideo?.id)throw new Error("Video tersimpan tetapi ID tidak diterima.");show("Video berhasil disimpan.","success");if(!u.searchParams.get("id"))location.reload();}catch(e){console.error(e);show(e?.message||"Gagal menyimpan video.","error");}finally{setButtons();if(!(auth.role==="editor"&&currentVideo?.status==="published"))[saveButton,draftButton,reviewButton,archiveButton].forEach(b=>b.disabled=false);}}

async function remove(){if(!currentVideo?.id)return;if(auth.role!=="admin")return show("Hanya Admin yang dapat menghapus video.","error");if(!confirm(`Hapus video “${currentVideo.title}”?`))return;try{await deleteVideo(currentVideo.id);location.href="videos.html";}catch(e){show(e?.message||"Gagal menghapus video.","error");}}

titleInput?.addEventListener("input",()=>{if(!slugManual)slugInput.value=slug(titleInput.value);updatePreview();});slugInput?.addEventListener("input",()=>{slugManual=true;});youtubeUrlInput?.addEventListener("input",updateYoutube);youtubeUrlInput?.addEventListener("change",updateYoutube);thumbnailInput?.addEventListener("input",updatePreview);
form?.addEventListener("submit",e=>{e.preventDefault();save("draft")});draftButton?.addEventListener("click",()=>save("draft"));reviewButton?.addEventListener("click",()=>save("review"));publishButton?.addEventListener("click",()=>save("published"));archiveButton?.addEventListener("click",()=>save("archived"));$("#hapus")?.addEventListener("click",remove);logoutButton?.addEventListener("click",async()=>{try{await logout();}catch(e){show(e?.message||"Gagal keluar.","error");}});

async function init(){try{show("Memuat...");if(!window.MandalaSupabase)throw new Error("Supabase client Mandala belum dimuat.");if(!await loadAuth())return;await loadCategories();const id=new URLSearchParams(location.search).get("id");if(id)await loadExisting(id);else{statusInput.value="draft";updatePreview();setButtons();show("Siap membuat video.");}}catch(e){console.error(e);show(e?.message||"Gagal memuat editor video.","error");}}
init();